### ISSUE TITLE
Build fails with compiler exceptions in v2.17.8

### ISSUE THREAD

**Issue by fschon** [openmdx/openmdx#39]
I am trying to build from source according to the instructions at https://github.com/openmdx/openmdx-documentation/blob/master/Sdk/BuildFromSource.md

I have grade 6.9 installed, java 1.8 and Java 11. 
I have set the JRE_18 and JDK_11 env variables. 
Cloned the repo and checked out openmdx-v2.17.8

"gradle clean" runs without error.
"gradle assemble" fails with the following compile errors:

> Task :security:compileJava FAILED
/home/franz/build/openmdx/security/src/main/java/org/openmdx/resource/ldap/ldif/Repository.java:100: error: Repository is not abstract and does not override abstract method exceptionCaught() in LdapConnection
class Repository implements LdapConnection {
^
/home/franz/build/openmdx/security/src/main/java/org/openmdx/resource/ldap/spi/Connection.java:95: error: Connection is not abstract and does not override abstract method exceptionCaught() in LdapConnection
class Connection extends AbstractConnection implements LdapConnection {
^
Note: /home/franz/build/openmdx/security/src/main/java/org/openmdx/resource/ldap/ldif/Repository.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

**Comment by fschon** [comment]
This can be fixed by changing the apache-ldap-api dependency from 
implementation("org.apache.directory.api:apache-ldap-api:2.0.+")
to
implementation("org.apache.directory.api:apache-ldap-api:2.0.0")

**Comment by wfro64** [comment]
The method org.apache.directory.ldap.client.api.LdapConnection.exceptionCaught was added since apache-ldap-api:2.0.2. Implementation must be added to security/src/main/java/org/openmdx/resource/ldap/ldif/Repository.java and security/src/main/java/org/openmdx/resource/ldap/spi/Connection.java
