### ISSUE TITLE
openmdx-base.jar: META-INF/orm.xml is missing

### ISSUE THREAD

**Issue by wfro64** [openmdx/openmdx#93]
META-INF/orm.xml is missing in openmdx-base.jar.

`zipTree(File(buildDir, "generated/sources/model/openmdx-" + project.getName() + ".openmdx-xmi.zip"))`

should be added to the from clause of the "openmdx-base.jar" task in core/build.gradle.kts.

NOTE 1: openmdx-security.jar, openmdx-portal.jar are OK

NOTE 2: openmdxBaseIncludes is OK

**Comment by DlRTY-HARRY** [comment]
`./gradlew clean` will delete the patform deliver directory (e.g. `./jre-1.8`), too.
