### ISSUE TITLE
Missing META-INF/orm.xml in openmdx-base.jar

### ISSUE THREAD

**Issue by wfro64** [openmdx/openmdx#98]
With openmdx-2.18.8 and later META-INF/orm.xml is missing in openmdx-base.jar.

### Steps to reproduce

Create a Dockerfile with the following content

```
FROM ubuntu:latest
ENV PLATFORM jre-11
ENV HOME /root

# Install ant, jdk, ...
RUN apt-get update
RUN apt-get -y install \
  software-properties-common

RUN add-apt-repository ppa:openjdk-r/ppa && apt-get update && apt-get -y install \
  net-tools \
  openjdk-17-jdk \
  wget \
  unzip \
  ant \
  git
```

then build and run the docker image

>  docker build -t openmdx .
> sudo docker run -it openmdx bash

In running container

```
export JRE_18=/usr/lib/jvm/java-8-openjdk-amd64/jre
git clone https://github.com/openmdx/openmdx.git openmdx
cd openmdx
./gradlew --refresh-dependencies assemble
jar tf ./jre-1.8/core/lib/openmdx-base.jar | grep orm.xml
```

### Expected

```
jar tf ./jre-1.8/core/lib/openmdx-base.jar | grep orm.xml
META-INF/orm.xml
```

### Workaround

```
rm ./jre-1.8/core/lib/openmdx-base.jar
./gradlew --refresh-dependencies assemble
```

### Note
The build outputs many warnings of the form

`w: file:///openmdx/security/build.gradle.kts:177:21: 'getter for buildDir: File!' is deprecated. Deprecated in Java`

**Comment by javac9** [comment]
Successfully reproduced for `openmdx-v2.18.9`, `openmdx-v2.18.8` **but also** for `openmdx-v2.18.7` and `openmdx-v2.18.6`.
